---
- hosts: webservers
  become: True
  tasks:
    - name: install packages
      apt:
        name: "apache2"
        state: "present"
    - name: star apache server
      service:
        name: apache2
        state: started
        enabled: True
    - name: deploy static website
      copy:
        src: dist/
        dest: /var/www/html